### ISSUE TITLE
Fails in sdk 21

### ISSUE THREAD

**Issue by dantreble** [Unity-Technologies/GooglePlayLicenseVerification#1]
The service binder code has changed as per...
http://commonsware.com/blog/2014/06/29/dealing-deprecations-bindservice.html
https://www.reddit.com/r/androiddev/comments/2jspqi/got_many_recent_reports_of_license_verification/

I'd fix it, but I uninstalled eclipse and I can't bring myself to re install it today... so I'm just going back to sdk 19 :-)

**Comment by Over17** [comment]
Fixed by https://github.com/Unity-Technologies/GooglePlayLicenseVerification/commit/645bf305d608545338bfea9f09b02118df09fc26.
