### ISSUE TITLE
Required 64 bits for Google Play

### ISSUE THREAD

**Issue by Jotamaza** [Unity-Technologies/GooglePlayLicenseVerification#11]
Hi there,

After creating the APK and upload it to Google Play Console (with IL2CPP and ARM64 selected), the console gives an error about the lack of 64 bits native code version.

So I've tried to follow the documentation to recompile the sources, but I found it obsolete/deprecated. As I'm not a Java / Android developer I am blocked here. Can you build a jar including 64 bits version or update de build documentation using Android Studio?

Thanks!

**Comment by Over17** [comment]
Hi!

This plugin has no native libraries, so has no effect on the warning you've mentioned.

However, if you have selected arm64 and still get the error, check if you have x86 selected - and uncheck it if it is.

**Comment by Jotamaza** [comment]
Thanks Over17. That solved the warning.

Sorry, my fault.
