### ISSUE TITLE
"LU" extras is empty against NOT_LICENSED 

### ISSUE THREAD

**Issue by Shahab-Mirza** [Unity-Technologies/GooglePlayLicenseVerification#3]
I changed the  public key with my  application public  key but not getting any information about license URL.  For testing purposes ,We have added our license test account  on Play Console and set the license test response and also signed into Play Store App with same test account on device but not getting detail page URL of the app against "LU" key.
![screenshot_20190110-124751](https://user-images.githubusercontent.com/16739602/51318491-4bb60e00-1a7c-11e9-9bc7-1ae7e70b606d.png)

**Comment by sourav-paul** [comment]
You got any solution regarding this?

**Comment by v01pe** [comment]
As far as I can tell, the response code you're seeing (on the screenshot) is LICENSED, and then LU being empty is fine…
I found the list of possible response codes here:

https://github.com/google/play-licensing/blob/master/lvl_library/src/main/java/com/google/android/vending/licensing/LicenseValidator.java
