### ISSUE TITLE
Unable to instantiate activity ComponentInfo error

### ISSUE THREAD

**Issue by sam-eller** [Unity-Technologies/GooglePlayLicenseVerification#4]
Android build has error:
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.company.appname/com.unity3d.player.UnityPlayerProxyActivity}

Because the Main Activity is in com.unity3d.player.UnityPlayerProxyActivity instead of com.unity3d.player.UnityPlayerActivity. 
Kind of annoying that it came like this.

**Comment by Over17** [comment]
Fixed in #5 - please let know if it works for you.
